---
editor: 
  markdown: 
    wrap: 72
---

# Welcome!

## Date and time

::: callout-note
🗓 13 June 2025

🕰️ 09:30 - 16:30
:::

## Location

::: {.callout-note icon="false"}
## 🏛️ Aarhus University

Eduard Biermann Auditorium [(Building 1252, Room
204)](https://www.au.dk/om/organisation/find-au/bygningskort/)

Bartholins Allé 3

8000 Aarhus C, Denmark

![Lakeside Auditoriums at Aarhus University. [Image from
WikiMedia](https://commons.wikimedia.org/wiki/File:S%C3%B8auditorierne_(maj_01).jpg)](/images/søauditorierne.jpg){#fig-auditoriums}
:::

## Background

As diabetes prevalence increases globally, there is an increasing need
to have up to date insights into the key numbers that define the
direction of our public health policies and setup of clinical attention.

Demographic analyses based on routinely registered data with
population-wide coverage have provided an excellent way of obtaining
these important insights. However, even amongst countries with
well-developed register systems there are differences that make it
difficult to generate direct comparisons.

Furthermore, as new specific areas of attention develop and new data
sources become available, coordination and joint development of methods
and expertise is necessary. This 1-day symposium aims to explore some of
these themes by presenting the experiences of some of the global experts
in the field. The expectation is that the discussions that emerge from
the symposium will serve to define a roadmap for standardization,
development of methods, education and joint research in the field.

### The target audience

Researchers (including PhD students and postdoctoral researchers)
working with register-based and epidemiological studies of diabetes, its
causes and consequences at the population level.

## Program (draft)

| Start | End | Title | Speaker |
|----|----|----|----|
| *09:30* | *10:00* | *Coffee* | *-* |
| 10:00 | 10:15 | Welcome and Introduction | Daniel Witte / Henrik Støvring |
| 10:15 | 10:50 |  | Dianna Magliano |
| 10:50 | 11:25 | Needed evolution of registries to accommodate the changing epidemiology | Edward Gregg |
| 11:25 | 12:00 |  | Sarah Wild |
| *12:00* | *13:00* | *Lunch* | *-* |
| 13:00 | 13:10 | Short Presentation 1 | Young researcher 1 |
| 13:10 | 13:20 | Short Presentation 2 | Young researcher 2 |
| 13:20 | 13:30 | Short Presentation 3 | Young researcher 3 |
| 13:30 | 13:40 | Short Presentation 4 | Young researcher 4 |
| 13:40 | 13:50 | Short Presentation 5 | Young researcher 5 |
| 13:50 | 14:00 | Short Presentation 6 | Young researcher 6 |
| 14:00 | 14:15 | Population-wide diabetes risk prediction: Plans for the DP-Next study | Daniel Witte |
| 14:15 | 14:35 | Methodological challenges of risk prediction for population screening | Henrik Støvring |
| *14:35* | *15:00* | *Coffee* | *-* |
| 15:00 | 15:35 |  | Bendix Carstensen |
| 15:35 | 16:15 | Discussion: What is the roadmap for future collaboration on this work? | All |
| 16:15 |  | Final words and end of seminar |  |

: Draft Program {tbl-colwidths="\[10,10,50,30\]" .striped}

### Speakers

| Name | Affiliation |
|----|----|
| Prof. Sarah Wild | University of Edinburgh, UK |
| Prof. Dianna Magliano | Baker Heart and Diabetes Institute, Melbourne, Australia (and visiting professor in Denmark in 2025) |
| Prof. Edward Gregg | Imperial College London, UK and Royal College of Surgeons in Ireland, Dublin, Ireland |
| Mr. Bendix Carstensen | Steno Diabetes Center Copenhagen |
| Prof. Henrik Støvring | Steno Diabetes Center Aarhus |
| Prof. Daniel Witte | Aarhus University / Steno Diabetes Center Aarhus |

Speaker list {tbl-colwidths="\[30,50\]" .striped}

::: {.callout-caution icon="false"}
## 🏛️## Registration

Please follow this [link to
register](https://rm.plan2learn.dk/kursusvalg.aspx?id=133889) for the
symposium. During registration, you can indicate whether you would like
to give a short, 10 minute presentation on your work related to diabetes
registers, demography, or related methods.

If it turns out that you will not be able to attend after you have
registered, please do not forget to cancel your registration.
:::
